### PR TITLE
changed product page

### PR DESCRIPTION
**Pull request by HimaghnaDas**

### CODE REVIEW

**Comment by rohan26062001** [comment]
@HimaghnaDas please work on the colour combination, it looks pretty basic
<br>
image

**Comment by HimaghnaDas** [comment]
@rohan26062001 this colour?
denim

**Comment by kanisht09** [comment]
@HimaghnaDas it would be better if u can share ur ideas in the group and also today rohan will push the navbar (which is basically based on a dark theme) and Carousel has already been pushed so maybe it will be a help.

**Comment by rohan26062001** [comment]
@HimaghnaDas see, a lot more is to be improved, 
- The product image is not aligned properly
- We'll use Dark Theme on our website. so change the colour according to that

Try to copy this:<br>
image

**Comment by rohan26062001** [comment]
@Rahul-Roy-21 Bhai, please help him!!!

**Pull request closed without merging**
